service: blog

image: veroisoardi/blog

servers:
  web:
    - 159.89.232.34

proxy:
  ssl: true
  host: recetas.veroisoardi.com.ar

registry:
  username: veroisoardi
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - POSTGRES_USER
  clear:
    RACK_ENV: production
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"


asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
  db:
    image: postgres:17
    host: 159.89.232.34
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_DB: blog_production
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    files:
      - config/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data

ssh:
  user: deploy